name: Format
on:
  push:
    branches-ignore:
      - main
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: " --aosp --replace"